import re
from typing import List, Dict

import pandas as pd
import streamlit as st
from transformers import pipeline

MODEL_NAME = "distilbert-base-uncased-finetuned-sst-2-english"
NEUTRAL_THRESHOLD = 0.60
MAX_HISTORY = 10
SAMPLE_TWEETS = [
    "I loved the new product launch today!",
    "The service was okay, but the wait time was too long.",
    "I am so disappointed by this update.",
]

@st.cache_resource
def load_sentiment_model() -> pipeline:
    """Load the sentiment analysis pipeline once and reuse it."""
    return pipeline("sentiment-analysis", model=MODEL_NAME)

@st.cache_data
def clean_tweet(text: str) -> str:
    """Return cleaned tweet text or an empty string if no valid content exists."""
    if text is None:
        return ""
    text = text.strip()
    text = re.sub(r"https?://\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"#", "", text)
    return text.strip()

@st.cache_data
def has_alpha(text: str) -> bool:
    """Detect whether the tweet contains at least one alphabetic character."""
    return bool(re.search(r"[A-Za-z]", text))

def analyze_sentiment(model: pipeline, text: str) -> Dict[str, object]:
    """Analyze sentiment and return a normalized label and score."""
    scores = model(text, return_all_scores=True)[0]
    score_map = {item["label"]: item["score"] for item in scores}
    top = max(scores, key=lambda item: item["score"])
    label = top["label"].upper()
    top_score = float(top["score"])

    if top_score < NEUTRAL_THRESHOLD:
        label = "NEUTRAL"
    return {
        "label": label,
        "score": round(top_score * 100, 2),
        "details": score_map,
    }

def render_result(label: str, score: float) -> None:
    """Render the sentiment prediction with an icon and styling."""
    st.subheader("📊 Sentiment Result")
    if label == "POSITIVE":
        st.success(f"😊 Positive — {score}% confidence")
    elif label == "NEGATIVE":
        st.error(f"😡 Negative — {score}% confidence")
    else:
        st.info(f"😐 Neutral — {score}% confidence")

    st.write(
        "This result is generated by a transformer-based sentiment model. "
        "Neutral labels are returned when the prediction confidence is low."
    )

def append_history(entry: Dict[str, object]) -> None:
    """Save recent sentiment checks in the session state."""
    if "history" not in st.session_state:
        st.session_state.history = []
    st.session_state.history.insert(0, entry)
    st.session_state.history = st.session_state.history[:MAX_HISTORY]

def render_history() -> None:
    """Display recent text sentiment checks."""
    if "history" not in st.session_state or not st.session_state.history:
        return
    with st.expander("🕘 Recent Sentiment Checks", expanded=False):
        history = pd.DataFrame(st.session_state.history)
        st.dataframe(history)

def analyze_dataframe(df: pd.DataFrame, column: str, model: pipeline) -> pd.DataFrame:
    """Analyze all tweets in a DataFrame column and return a results DataFrame."""
    rows: List[Dict[str, object]] = []
    for _, row in df.iterrows():
        text = clean_tweet(str(row.get(column, "")))
        if not text or not has_alpha(text):
            rows.append({"tweet": text, "label": "INVALID", "score": 0.0})
            continue
        prediction = analyze_sentiment(model, text)
        rows.append({
            "tweet": text,
            "label": prediction["label"],
            "score": prediction["score"],
        })
    return pd.DataFrame(rows)

def main() -> None:
    st.set_page_config(
        page_title="Twitter Sentiment Analysis",
        page_icon="🐦",
        layout="wide",
        initial_sidebar_state="expanded",
    )

    st.markdown(
        "<style>"
        "section.main > div.block-container { padding-top: 1rem; }"
        "</style>",
        unsafe_allow_html=True,
    )

    st.markdown("# 🐦 Twitter Sentiment Analysis")
    st.write(
        "Analyze a single tweet or upload a CSV file to score many tweets at once. "
        "The app supports model-based sentiment prediction, results visualization, and download-ready reports."
    )

    sidebar = st.sidebar
    sidebar.header("What you can do")
    sidebar.write(
        "- ✅ Analyze one tweet instantly\n"
        "- ✅ Upload a CSV and score many tweets\n"
        "- ✅ View summary metrics and charts\n"
        "- ✅ Download predictions as CSV"
    )
    sidebar.divider()
    sidebar.header("Model details")
    sidebar.write(
        "The app uses Hugging Face `transformers` for sentiment analysis. "
        "Low-confidence predictions are classified as neutral to improve tweet-style results."
    )
    sidebar.markdown("---")
    sidebar.header("Example tweets")
    for example in SAMPLE_TWEETS:
        sidebar.write(f"- {example}")

    sentiment_model = load_sentiment_model()

    single_col, batch_col = st.columns([1, 1])

    with single_col:
        st.subheader("✍️ Analyze a single tweet")
        single_text = st.text_area(
            "Enter tweet text:",
            placeholder="e.g. I really enjoyed the event today!",
            height=180,
        )
        if st.button("Analyze Tweet", key="single"):
            cleaned_text = clean_tweet(single_text)
            if not cleaned_text:
                st.warning("Please enter a tweet to analyze.")
            elif not has_alpha(cleaned_text):
                st.warning("Please enter a valid tweet containing text.")
            else:
                try:
                    prediction = analyze_sentiment(sentiment_model, cleaned_text)
                    render_result(prediction["label"], prediction["score"])
                    append_history({
                        "tweet": cleaned_text,
                        "label": prediction["label"],
                        "score": prediction["score"],
                    })
                except Exception as exc:
                    st.error("Unable to analyze the tweet right now. Please try again later.")
                    st.exception(exc)

    with batch_col:
        st.subheader("📁 Batch CSV upload")
        uploaded_file = st.file_uploader(
            "Upload a CSV file with tweet text",
            type=["csv"],
            label_visibility="visible",
        )
        if uploaded_file is not None:
            try:
                df = pd.read_csv(uploaded_file)
                text_columns = [
                    col for col in df.columns if df[col].dtype == object or col.lower() in ["text", "tweet", "content"]
                ]
                if not text_columns:
                    st.warning("No text column detected. Please upload a CSV with a text field.")
                else:
                    selected_column = st.selectbox("Select the tweet text column", text_columns)
                    if st.button("Analyze CSV", key="batch"):
                        with st.spinner("Analyzing tweets..."):
                            results = analyze_dataframe(df, selected_column, sentiment_model)
                        st.success("Batch sentiment analysis complete.")
                        st.dataframe(results)
                        summary = results["label"].value_counts().rename_axis("label").reset_index(name="count")
                        st.bar_chart(summary.rename(columns={"label": "index", "count": "value"}).set_index("index"))
                        csv_data = results.to_csv(index=False).encode("utf-8")
                        st.download_button(
                            "📥 Download analyzed tweets",
                            data=csv_data,
                            file_name="sentiment_results.csv",
                            mime="text/csv",
                        )
            except Exception as exc:
                st.error("Unable to read the uploaded file. Please verify that it is a valid CSV.")
                st.exception(exc)

    st.divider()

    metrics_col1, metrics_col2, metrics_col3 = st.columns(3)
    if "history" in st.session_state and st.session_state.history:
        history_df = pd.DataFrame(st.session_state.history)
        positive = int((history_df["label"] == "POSITIVE").sum())
        negative = int((history_df["label"] == "NEGATIVE").sum())
        neutral = int((history_df["label"] == "NEUTRAL").sum())
        metrics_col1.metric("Positive", positive, delta=positive - negative)
        metrics_col2.metric("Negative", negative, delta=negative - neutral)
        metrics_col3.metric("Neutral", neutral, delta=neutral - positive)
    else:
        metrics_col1.metric("Positive", "—")
        metrics_col2.metric("Negative", "—")
        metrics_col3.metric("Neutral", "—")

    render_history()

    with st.expander("💡 Tips for better results", expanded=False):
        st.markdown(
            "- Use natural language instead of abbreviations when possible.\n"
            "- Avoid submitting text that is only links or hashtags.\n"
            "- For best results, keep tweets concise and clear."
        )

if __name__ == "__main__":
    main()


